# Generated by Django 5.0.6 on 2024-07-27 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('lesson_description', models.TextField()),
                ('lesson_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('teacher_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lesson_start_date', models.DateField(auto_now_add=True)),
                ('lesson_end_date', models.DateField(auto_now=True)),
                ('lessons_taken', models.PositiveSmallIntegerField(default=0)),
                ('people', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.category')),
            ],
        ),
    ]
