# Generated by Django 5.0.6 on 2024-07-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_start_date',
            field=models.DateField(),
        ),
    ]
