# Generated by Django 5.0.6 on 2024-07-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_lesson_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_end_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_start_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lessons_taken',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='people',
        ),
    ]
